In [9]:
import csv
import numpy as np

file_path = 'files/feature_table.csv'
data = []
with open(file_path, newline='') as csvfile:
    csv_reader = csv.reader(csvfile)
    for row in csv_reader:
        del row[0]
        data.append(row)
del data[0]
for row in data:
   del row[0]

for i in range(len(data)):
    for j in range(len(data[i])):
        if float(data[i][j]) > 0:
            data[i][j] = 1
        else:
            data[i][j] = 0

matrix_size = len(data)
mat = np.array(data)
matriz_adj = np.zeros((matrix_size, matrix_size)) #criando a matriz de adjacência com zeros

for i in range(len(data)):
    for j in range(i + 1, len(data)):
        # Verificando se duas bactérias estão presentes em mais de três pacientes
        if np.sum(mat[i] & mat[j]) >= 3:
            matriz_adj[i][j] = 1
            matriz_adj[j][i] = 1
#matriz_original = [[0, 0, 1], [1, 0, 1], [1, 0, 0], [1, 1, 1], [1, 1, 0]]





N = {
    i: set(num for num, j in enumerate(row) if j)
    for i, row in enumerate(matriz_adj)
}

def BronKerbosch1(P, R=None, X=None):
    P = set(P) # 1
    R = set() if R is None else R # 1
    X = set() if X is None else X # 1
    if not P and not X: # 1
        yield R # 1
    while P:
        v = P.pop() # 1
        yield from BronKerbosch1(
            P=P.intersection(N[v]), R=R.union([v]), X=X.intersection(N[v])) # 3^n
        X.add(v) # 1

P = N.keys()
print(list(BronKerbosch1(P)))


In [4]:
import numpy as np

# Tabela de presença das bactérias nos pacientes
bacteria_table = np.array([
    [1, 0, 1, 1, 0],
    [1, 1, 0, 1, 0],
    [0, 1, 1, 0, 1],
    [0, 1, 1, 0, 1]
])

# Inicializando a matriz de adjacência com zeros
adjacency_matrix = np.zeros((4, 4), dtype=int)

# Criando a matriz de adjacência com base na condição
for i in range(4):
    for j in range(i + 1, 4):
        # Verificando se duas bactérias estão presentes em mais de três pacientes
        if np.sum(bacteria_table[i] & bacteria_table[j]) >= 3:
            adjacency_matrix[i, j] = 1
            adjacency_matrix[j, i] = 1

print("Matriz de Adjacência:")
print(adjacency_matrix)


Matriz de Adjacência:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 1]
 [0 0 1 0]]
